name: dart_serial_port
description: Serial Port for Dart (FFI bindings to libserialport,
  a minimal C-library created by the sigrok).
version: 0.0.6
homepage: https://github.com/jpnurmi/dart_serial_port
repository: https://github.com/jpnurmi/dart_serial_port
issue_tracker: https://github.com/jpnurmi/dart_serial_port/issues

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  ffi: ^0.1.3

dev_dependencies:
  ffigen: ^1.2.0
  lint: ^1.0.0
  test: ^1.15.3
  test_coverage: ^0.4.3
