name: dart_serial_port
description: Serial Port for Dart (FFI bindings to libserialport,
  a minimal C-library created by the sigrok).
version: 0.0.6
homepage: https://github.com/jpnurmi/dart_serial_port
repository: https://github.com/jpnurmi/dart_serial_port
issue_tracker: https://github.com/jpnurmi/dart_serial_port/issues

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  ffi: ^0.1.3

dev_dependencies:
  ffigen: 0.1.5
  pedantic: ^1.9.2
  test: ^1.15.3
  test_coverage: ^0.4.3

ffigen:
  name: LibSerialPort
  description: >-
    libserialport: cross-platform library for accessing serial ports
  output: 'lib/src/bindings.dart'
  headers:
    - '/usr/local/include/libserialport.h'
  structs:
    include:
      matches:
        - 'sp_.*'
  enums:
    include:
      matches:
        - 'sp_.*'
  macros:
    include:
      matches:
        - 'SP_.*'
  compiler-opts: '-I/usr/lib/llvm-7/lib/clang/7.0.1/include'
