name: dart_serial_port
description: Serial Port for Dart (FFI bindings to libserialport,
  a minimal C-library created by the sigrok).
version: 0.0.7
homepage: https://github.com/jpnurmi/dart_serial_port
repository: https://github.com/jpnurmi/dart_serial_port
issue_tracker: https://github.com/jpnurmi/dart_serial_port/issues

environment:
  sdk: '>=2.12.0-133.2.beta <3.0.0'

dependencies:
  ffi: ^0.2.0-nullsafety.1

dev_dependencies:
  #ffigen: ^1.2.0
  lint: ^1.5.1
  test: ^1.16.0-nullsafety.13
